import Anthropic from "@anthropic-ai/sdk";
import { kv } from "@vercel/kv";
import { SYSTEM_PROMPT } from "../lib/systemPrompt.js";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const MODEL = "claude-sonnet-4-6";
const ROTATION_KEY = "ae_heartbeat_rotation";
const QUESTIONS_PER_RUN = 2;
const MAX_BLOCK = 2900; // Slack section text hard limit is 3000

function loadQuestions() {
  try {
    const parsed = JSON.parse(process.env.HEARTBEAT_QUESTIONS || "[]");
    return Array.isArray(parsed)
      ? parsed.filter((q) => typeof q === "string" && q.trim().length > 0)
      : [];
  } catch (e) {
    console.error("Bad HEARTBEAT_QUESTIONS JSON:", e);
    return [];
  }
}

async function diagnose(question) {
  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 900,
    thinking: { type: "disabled" },
    output_config: { effort: "low" },
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: question }],
  });
  return (msg.content || [])
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("\n")
    .trim();
}

// GitHub-flavored markdown -> Slack mrkdwn (Slack uses single-asterisk bold, no headings)
function toSlackMrkdwn(md) {
  return md
    .replace(/\s*—\s*/g, " - ") // em-dash -> spaced hyphen (no-em-dash preference)
    .replace(/–/g, "-") // en-dash (ranges) -> hyphen
    .replace(/^#{1,6}\s*(.+)$/gm, "*$1*")
    .replace(/\*\*(.+?)\*\*/g, "*$1*");
}

// split long text into <=MAX_BLOCK chunks on line boundaries
function chunk(text) {
  const out = [];
  let buf = "";
  for (const line of text.split("\n")) {
    if (buf.length + line.length + 1 > MAX_BLOCK) {
      if (buf) out.push(buf);
      buf = line.length > MAX_BLOCK ? line.slice(0, MAX_BLOCK) : line;
    } else {
      buf = buf ? buf + "\n" + line : line;
    }
  }
  if (buf) out.push(buf);
  return out.length ? out : [text.slice(0, MAX_BLOCK)];
}

function buildBlocks(pairs) {
  const blocks = [
    {
      type: "header",
      text: { type: "plain_text", text: "🤖 AI Head Coach · Automated Bot", emoji: true },
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: "Biweekly auto-run · 2 recurring questions from Gold and Silver office hours · generated by the Advisory Engine, not a human coach.",
        },
      ],
    },
    { type: "divider" },
  ];
  pairs.forEach((p, i) => {
    blocks.push({
      type: "section",
      text: { type: "mrkdwn", text: `*▸ Q${i + 1}:* ${p.q}` },
    });
    for (const c of chunk(toSlackMrkdwn(p.a))) {
      blocks.push({ type: "section", text: { type: "mrkdwn", text: c } });
    }
    if (i < pairs.length - 1) blocks.push({ type: "divider" });
  });
  return blocks;
}

export default async function handler(req, res) {
  // Only the Vercel cron (or a caller holding the secret) may trigger this.
  const secret = process.env.CRON_SECRET;
  const auth = req.headers["authorization"] || "";
  if (!secret || auth !== `Bearer ${secret}`) {
    return res.status(401).json({ error: "unauthorized" });
  }

  const questions = loadQuestions();
  if (questions.length === 0) {
    return res.status(500).json({ error: "no_questions_configured" });
  }

  const webhook = process.env.SLACK_HEARTBEAT_WEBHOOK;
  if (!webhook) {
    return res.status(500).json({ error: "no_slack_webhook" });
  }

  // Rotation index in KV. This read + write also keeps the Upstash DB warm.
  let idx = 0;
  try {
    idx = (await kv.get(ROTATION_KEY)) || 0;
  } catch (e) {
    console.error("KV read error (proceeding):", e);
  }

  const picked = [];
  for (let i = 0; i < QUESTIONS_PER_RUN; i++) {
    picked.push(questions[(idx + i) % questions.length]);
  }

  let pairs;
  try {
    const answers = await Promise.all(picked.map((q) => diagnose(q)));
    pairs = picked.map((q, i) => ({ q, a: answers[i] || "(no response)" }));
  } catch (e) {
    console.error("Anthropic error:", e);
    return res.status(502).json({ error: "diagnosis_failed", detail: String(e).slice(0, 300) });
  }

  // Advance rotation (KV write = keep-alive touch).
  const nextIndex = (idx + QUESTIONS_PER_RUN) % questions.length;
  try {
    await kv.set(ROTATION_KEY, nextIndex);
  } catch (e) {
    console.error("KV write error:", e);
  }

  try {
    const resp = await fetch(webhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: "🤖 AI Head Coach - biweekly auto-diagnosis (bot)",
        blocks: buildBlocks(pairs),
      }),
    });
    if (!resp.ok) {
      const body = await resp.text();
      throw new Error(`slack ${resp.status}: ${body.slice(0, 200)}`);
    }
  } catch (e) {
    console.error("Slack post error:", e);
    return res.status(502).json({ error: "slack_failed", detail: String(e).slice(0, 300) });
  }

  return res.status(200).json({ ok: true, asked: picked, nextIndex });
}
